[WIP] StudyplusRecordのdurationプロパティへ24時間上限を追加
studyplus/Studyplus-iOS-SDK-V2 pull request #13
Opened 2019-06-14 09:25 UTC by m-yamada04

## 背景

- 指定した日付の中で勉強した時間の投稿を受け付けるというのが基本的な仕様
  - SDKでは24時間より多く指定が可能で、上記の意図と異なる使い方ができてしまう

##  対応
- StudyplusRecordのdurationプロパティにて、24時間(86400)より上の値を指定して投稿を実行した際にエラーを返却

- 上記の値が上限の場合、StudyplusRecordのdurationプロパティがDouble型である必要がないためInt型へ変更

## 既存アプリへの影響
- StudyplusRecordのdurationプロパティがDouble型想定の`StudyplusRecord(duration:recordedAt:amount:comment:)` をdeprecated指定
  - 既存と同様に動作はするよう実装

2019-06-14 10:44 UTC, masashi-sutou requested changes

2019-06-14 10:44 UTC, masashi-sutou commented on Demo/ViewController.swift
> +        let record: StudyplusRecord = StudyplusRecord(duration: Int(duration), recordedAt: Date(), amount: recordAmount, comment: "Today, I studied like anything.")
Intて言ってしまいましたが、0...(24 * 60 * 60) でバリデーションしてればいいので、そのままdoubleでいいですね 😓

2019-06-14 11:10 UTC, koishi approved these changes
@m-yamada04 
私からは特にありません！

2019-06-17 07:18 UTC, m-yamada04 commented on Demo/ViewController.swift
> +        let record: StudyplusRecord = StudyplusRecord(duration: Int(duration), recordedAt: Date(), amount: recordAmount, comment: "Today, I studied like anything.")
>Intて言ってしまいましたが、0...(24 * 60 * 60) でバリデーションしてればいいので、そのまま Double でいいですね 😓
Intのイニシャライザを削除して、durationの型をDoubleへ戻しました！
https://github.com/studyplus/Studyplus-iOS-SDK-V2/pull/13/commits/454bf6739f87c59c211f3e1279e2bfc9ac7f6850

>小数で送られてきた場合を考慮して、floor でリクエスト寸前に整数に変えてあげればいい

単純にIntへキャストすると小数点切り捨ての動きをすることは確認できたのですが、明記した方がわかりやすいので対応しました！
https://github.com/studyplus/Studyplus-iOS-SDK-V2/pull/13/commits/ec0b80069790011df73d6c5cdbf9811d23dcc0c1

2019-06-17 07:54 UTC, m-yamada04 commented on Demo/ViewController.swift
> +        let record: StudyplusRecord = StudyplusRecord(duration: Int(duration), recordedAt: Date(), amount: recordAmount, comment: "Today, I studied like anything.")
floorなしでもIntキャストのみ時と挙動が同じなら不要とのことで削除しました。
https://github.com/studyplus/Studyplus-iOS-SDK-V2/pull/13/commits/6aa9e18448cbff588afc033cbfbca59b8a7de732

2019-06-17 08:06 UTC, masashi-sutou commented
LGTM 🎉

2019-06-17 08:07 UTC, masashi-sutou approved these changes

2019-06-17 09:48 UTC, merged